version: '3'
services:
  react:
    image: node:16
    restart: always
    volumes:
      - ./react:/app
    working_dir: /app
    command: ['npm','run','start']
    ports:
      - 3000:3000

  node:
    image: node:16
    restart: always
    volumes:
      - ./node:/app
    working_dir: /app
    command: ['node','index.js']
    ports:
      - 8000:8000